![Saber Technologies](https://1.bp.blogspot.com/-gFxi6dswqO0/WfmOUgT1YXI/AAAAAAAAA5E/tvVOOQFoo1gbOnmArmBXu54X44Kri3rzwCLcBGAs/s320/sabertechnologies.png)

<h1><center>NEURAL NETWORK</center></h1>

## Import

In [29]:
import numpy as np
from numpy import genfromtxt
import pandas as pd
from sklearn import preprocessing
from tkinter import *

## Sigmoid Activation Function

In [19]:
def sig(a):
    return 1/(1+np.exp(-a))

def derivative(b):
    return (b) * (1-b)

## Input Features And Labels

In [20]:
x = np.array([[1,0,0,1],
             [0,0,1,0],
             [0,1,0,1],
             [1,1,0,0],
             [1,0,0,1]])
print(x)
y = np.array([[1,0,0,1,1]]).T
print(y)

[[1 0 0 1]
 [0 0 1 0]
 [0 1 0 1]
 [1 1 0 0]
 [1 0 0 1]]
[[1]
 [0]
 [0]
 [1]
 [1]]


## Assign Weights

In [21]:
weights = 2 * np.random.random((4,5)) -1
weightsout = 2 * np.random.random((5,1)) -1
print(weights)
print("\n")
print(weightsout)

[[-0.84098076  0.03016644  0.39902984 -0.89451951 -0.17340677]
 [-0.75844768 -0.89836835  0.45605468 -0.72807513 -0.14572293]
 [ 0.80687508  0.52749777  0.8287055   0.35832139  0.41092267]
 [-0.71122325  0.1778529   0.5895715   0.19165613 -0.19430375]]


[[-0.83374237]
 [-0.60681523]
 [-0.65240148]
 [-0.90185916]
 [-0.00687272]]


## Traning

In [22]:
for i in range(60000) :
    l0 = x
    l1 = sig(np.dot(l0 , weights))
    l2 = sig(np.dot(l1 , weightsout))
    
    if i is 0:
        print("Initial Output")
        print(l2)
        print("\nErrors")
        
    error = y-l2
    
    if i % 10000 is 0:
        print(str(np.mean(np.abs((error)))))
    
    l2_delta = error * derivative(l2)
    l1_error = np.dot(l2_delta , weightsout.T)
    l1_delta = l1_error * derivative(l1)
    
    weightsout += np.dot(l1.T , l2_delta)
    weights += np.dot(l0.T , l1_delta)

print("\nFinal Output")
print(l2)

Initial Output
[[0.22139969]
 [0.12485537]
 [0.23633144]
 [0.2831642 ]
 [0.22139969]]

Errors
0.527044645448467
0.003840022668762981
0.0026452627909467224
0.002130603454414344
0.001828522230233567
0.0016245451350451515

Final Output
[[0.99881548]
 [0.0016239 ]
 [0.00161642]
 [0.99823343]
 [0.99881548]]


## Predict

In [25]:
new = sig(np.dot(np.array([int(input()),int(input()),int(input()),int(input())]),weights))
sig(np.dot(new , weightsout))

0
1
1
1


array([0.00020493])